# Generated by Django 4.2.5 on 2023-10-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactdb',
            new_name='contdb',
        ),
    ]
