# Generated by Django 4.2.5 on 2023-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_regdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regdb',
            new_name='regidb',
        ),
    ]
