# Generated by Django 4.2.5 on 2023-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_rename_regdb_regidb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('username', models.IntegerField(blank=True, max_length=50, null=True)),
                ('productname', models.IntegerField(blank=True, max_length=50, null=True)),
                ('des', models.IntegerField(blank=True, max_length=200, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
