# Generated by Django 4.2.5 on 2023-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='des',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='productname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
