# Generated by Django 4.2.4 on 2023-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.CharField(blank=True, max_length=100, null=True)),
                ('cimg', models.ImageField(blank=True, null=True, upload_to='profle_img')),
            ],
        ),
    ]
