# Generated by Django 4.2.5 on 2023-09-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='cname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
