# Generated by Django 4.2.5 on 2023-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_regdb_delete_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regdb',
        ),
    ]
